### ISSUE TITLE
External URLs

### ISSUE THREAD

**Issue by clloyd** [guardian/editorial-viewer#12]
How are we planning on handling external urls? Should we be able to handle them? Should we prevent them from being loaded?

**Comment by alastairjardine** [comment]
Open in new window? Is that even possible?

**Comment by clloyd** [comment]
I was thinking we make it work as expected (stay within the viewer).. people could be wanting to make sure the sire they linked to works on mobile? but ensure that the mobile checked checkbox is forced to enabled (greyed out?) for those urls.

**Comment by clloyd** [comment]
#11 Will need to solve this issue
